# Generated by Django 5.0.2 on 2024-02-24 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_department_position_employee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carbrand',
            options={'verbose_name': 'Бренд машины', 'verbose_name_plural': 'Бренды машин'},
        ),
    ]
