# Generated by Django 5.0.2 on 2024-02-24 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_carbrand_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='is_available',
            field=models.BooleanField(default=True, editable=False, verbose_name='Доступна'),
        ),
    ]
