# Generated by Django 5.0.2 on 2024-03-02 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_delete_drivercar'),
        ('employees', '0005_alter_position_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.car')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivers.driver', verbose_name='Водитель')),
            ],
            options={
                'verbose_name': 'Водитель-Машина',
                'verbose_name_plural': 'Водители-Машины',
                'db_table': 'autopark_drivers_cars',
            },
        ),
    ]
