# Generated by Django 5.0.2 on 2024-03-02 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_delete_drivercar'),
        ('employees', '0007_cardriverassignment_delete_drivercar'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cardriverassignment',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='cardriverassignment',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.car', unique=True, verbose_name='Машина'),
        ),
        migrations.AlterField(
            model_name='cardriverassignment',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivers.driver', unique=True, verbose_name='Водитель'),
        ),
    ]
