# Generated by Django 5.0.2 on 2024-03-02 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_delete_drivercar'),
        ('employees', '0008_alter_cardriverassignment_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardriverassignment',
            name='car',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employees.car', verbose_name='Машина'),
        ),
        migrations.AlterField(
            model_name='cardriverassignment',
            name='driver',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='drivers.driver', verbose_name='Водитель'),
        ),
    ]
