# Generated by Django 5.0.2 on 2024-02-12 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autopark', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarBrand',
            new_name='Car_Brand',
        ),
    ]
