# Generated by Django 5.0.2 on 2024-02-12 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autopark', '0002_rename_carbrand_car_brand'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Car_Brand',
            new_name='CarBrand',
        ),
        migrations.AlterField(
            model_name='driver',
            name='is_available',
            field=models.BooleanField(default=False, verbose_name='Доступен'),
        ),
        migrations.AlterModelTable(
            name='car',
            table='cars',
        ),
        migrations.AlterModelTable(
            name='carbrand',
            table='car_brands',
        ),
        migrations.AlterModelTable(
            name='client',
            table='clients',
        ),
        migrations.AlterModelTable(
            name='driver',
            table='drivers',
        ),
    ]
