# Generated by Django 5.0.2 on 2024-02-12 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autopark', '0003_rename_car_brand_carbrand_alter_driver_is_available_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='client',
            table=None,
        ),
    ]
