# Generated by Django 5.0.2 on 2024-02-12 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autopark', '0004_alter_client_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='car',
            table='autopark_cars',
        ),
        migrations.AlterModelTable(
            name='carbrand',
            table='autopark_car_brands',
        ),
        migrations.AlterModelTable(
            name='client',
            table='autopark_clients',
        ),
        migrations.AlterModelTable(
            name='driver',
            table='autopark_drivers',
        ),
    ]
